using System.Globalization;
using System.Text;
using Iaet.Core.Models;

namespace Iaet.Export.Generators;

/// <summary>
/// Generates a typed C# HTTP client from an <see cref="ExportContext"/>.
/// </summary>
public static class CSharpClientGenerator
{
    /// <summary>Generates the C# source file string.</summary>
    public static string Generate(ExportContext ctx)
    {
        ArgumentNullException.ThrowIfNull(ctx);

        var namespaceName = BuildNamespace(ctx.Session.TargetApplication);
        var sb = new StringBuilder();

        AppendFileHeader(sb, namespaceName);
        AppendRecords(sb, ctx);
        AppendClientClass(sb, ctx, namespaceName);

        return sb.ToString();
    }

    // ------------------------------------------------------------------

    private static string BuildNamespace(string targetApplication)
    {
        // Sanitize: keep letters/digits/dots, replace everything else with empty
        var clean = new StringBuilder();
        foreach (var ch in targetApplication)
        {
            if (char.IsLetterOrDigit(ch) || ch == '.')
                clean.Append(ch);
        }

        var name = clean.Length > 0 ? clean.ToString() : "GeneratedClient";
        return string.Create(CultureInfo.InvariantCulture, $"{name}.GeneratedClient");
    }

    private static void AppendFileHeader(StringBuilder sb, string namespaceName)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"namespace {namespaceName};");
        sb.AppendLine();
    }

    private static void AppendRecords(StringBuilder sb, ExportContext ctx)
    {
        foreach (var (_, schema) in ctx.SchemasByEndpoint)
        {
            sb.AppendLine(schema.CSharpRecord);
            sb.AppendLine();
        }
    }

    private static void AppendClientClass(StringBuilder sb, ExportContext ctx, string namespaceName)
    {
        // Extract simple class name from namespace (last segment)
        var lastDot = namespaceName.LastIndexOf('.') + 1;
        var className = namespaceName[lastDot..] + "ApiClient";

        sb.AppendLine(CultureInfo.InvariantCulture, $"public sealed partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly HttpClient _httpClient;");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"    public {className}(HttpClient httpClient)");
        sb.AppendLine("    {");
        sb.AppendLine("        _httpClient = httpClient;");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var group in ctx.EndpointGroups)
        {
            AppendMethod(sb, group);
        }

        sb.AppendLine("}");
    }

    private static void AppendMethod(StringBuilder sb, EndpointGroup group)
    {
        var methodName = BuildMethodName(group.Signature);
        var path = group.Signature.NormalizedPath;
        var httpMethod = group.Signature.Method;

        sb.AppendLine(CultureInfo.InvariantCulture,
            $"    public async Task<string?> {methodName}(CancellationToken ct = default)");
        sb.AppendLine("    {");

        switch (httpMethod)
        {
            case "GET":
            case "DELETE":
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"        var response = await _httpClient.{HttpClientMethodName(httpMethod)}(");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"            \"{path}\", ct).ConfigureAwait(false);");
                break;

            case "POST":
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"        var response = await _httpClient.PostAsync(");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"            \"{path}\", null, ct).ConfigureAwait(false);");
                break;

            case "PUT":
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"        var response = await _httpClient.PutAsync(");
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"            \"{path}\", null, ct).ConfigureAwait(false);");
                break;

            default:
                // PATCH and any other method: use SendAsync with HttpRequestMessage
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"        using var request = new HttpRequestMessage(new HttpMethod(\"{httpMethod}\"), \"{path}\");");
                sb.AppendLine(
                    "        var response = await _httpClient.SendAsync(request, ct).ConfigureAwait(false);");
                break;
        }

        sb.AppendLine("        response.EnsureSuccessStatusCode();");
        sb.AppendLine("        return await response.Content.ReadAsStringAsync(ct).ConfigureAwait(false);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Converts <c>GET /api/users/{id}</c> → <c>GetApiUsersIdAsync</c>.
    /// </summary>
    private static string BuildMethodName(EndpointSignature sig)
    {
        var sb = new StringBuilder();

        // Method prefix (e.g. "Get", "Post")
        var method = sig.Method;
        if (method.Length > 0)
        {
            sb.Append(char.ToUpperInvariant(method[0]));
            for (var i = 1; i < method.Length; i++)
                sb.Append(char.ToLowerInvariant(method[i]));
        }

        // Path segments
        var segments = sig.NormalizedPath.Split('/', StringSplitOptions.RemoveEmptyEntries);
        foreach (var seg in segments)
        {
            var clean = seg.Replace("{", string.Empty, StringComparison.Ordinal)
                           .Replace("}", string.Empty, StringComparison.Ordinal);
            if (clean.Length == 0)
                continue;
            sb.Append(char.ToUpperInvariant(clean[0]));
            sb.Append(clean[1..]);
        }

        sb.Append("Async");
        return sb.ToString();
    }

    private static string HttpClientMethodName(string httpMethod) => httpMethod switch
    {
        "GET"    => "GetAsync",
        "DELETE" => "DeleteAsync",
        _        => throw new ArgumentOutOfRangeException(nameof(httpMethod), httpMethod, "Unhandled HTTP method"),
    };
}
