using Iaet.Core.Abstractions;

namespace Iaet.Secrets;

/// <summary>
/// Reads and writes secrets as KEY=value lines in {rootDirectory}/{projectName}/.env.iaet files.
/// </summary>
public sealed class DotEnvSecretsStore : ISecretsStore
{
    private readonly string _rootDirectory;

    public DotEnvSecretsStore(string rootDirectory)
    {
        _rootDirectory = rootDirectory;
    }

    private string EnvFilePath(string projectName) =>
        Path.Combine(_rootDirectory, projectName, ".env.iaet");

    private static Dictionary<string, string> ParseFile(string path)
    {
        var dict = new Dictionary<string, string>(StringComparer.Ordinal);
        if (!File.Exists(path))
            return dict;

        foreach (var line in File.ReadAllLines(path))
        {
            var trimmed = line.Trim();
            if (trimmed.Length == 0 || trimmed.StartsWith('#'))
                continue;

            var eq = trimmed.IndexOf('=', StringComparison.Ordinal);
            if (eq <= 0)
                continue;

            var key = trimmed[..eq].Trim();
            var value = trimmed[(eq + 1)..];
            dict[key] = value;
        }

        return dict;
    }

    private static async Task WriteFileAsync(string path, Dictionary<string, string> entries)
    {
        var dir = Path.GetDirectoryName(path)!;
        Directory.CreateDirectory(dir);

        var lines = new List<string>
        {
            "# IAET secrets — do not commit this file",
            "# Generated by DotEnvSecretsStore",
            string.Empty
        };

        foreach (var (key, value) in entries.OrderBy(kv => kv.Key, StringComparer.Ordinal))
            lines.Add($"{key}={value}");

        await File.WriteAllLinesAsync(path, lines).ConfigureAwait(false);
    }

    public async Task SetAsync(string projectName, string key, string value, CancellationToken ct = default)
    {
        var path = EnvFilePath(projectName);
        var entries = ParseFile(path);
        entries[key] = value;
        await WriteFileAsync(path, entries).ConfigureAwait(false);
    }

    public Task<string?> GetAsync(string projectName, string key, CancellationToken ct = default)
    {
        var path = EnvFilePath(projectName);
        var entries = ParseFile(path);
        entries.TryGetValue(key, out var value);
        return Task.FromResult(value);
    }

    public Task<IReadOnlyDictionary<string, string>> ListAsync(string projectName, CancellationToken ct = default)
    {
        var path = EnvFilePath(projectName);
        IReadOnlyDictionary<string, string> entries = ParseFile(path);
        return Task.FromResult(entries);
    }

    public async Task RemoveAsync(string projectName, string key, CancellationToken ct = default)
    {
        var path = EnvFilePath(projectName);
        var entries = ParseFile(path);
        if (entries.Remove(key))
            await WriteFileAsync(path, entries).ConfigureAwait(false);
    }
}
